function FornaContainer(l,g){function k(b,d,e){return b.hasOwnProperty(d.num)?(val=parseFloat(b[d.num]),isNaN(val)?b[d.num]:e(val)):"white"}function d(b){b=n.selectAll("g.gnode");return b.filter(function(b){return b.selected})}function e(b){var d=b.radius+16,e=b.x-d,f=b.x+d,h=b.y-d,g=b.y+d;return function(d,G,k,l,m){if(d.point&&d.point!==b){var u=b.x-d.point.x,t=b.y-d.point.y,n=Math.sqrt(u*u+t*t),p=b.radius+d.point.radius;n<p&&(n=(n-p)/n*.1,b.x-=u*=n,b.y-=t*=n,d.point.x+=u,d.point.y+=t)}return G>
f||l<e||k>g||m<h}}function f(){if(!b.deaf&&!D){keyIsDown=!0;switch(d3.event.keyCode){case 16:D=!0;break;case 17:A=!0;break;case 67:b.centerView()}if(D||A)p.call(b.zoomer).on("mousedown.zoom",null).on("touchstart.zoom",null).on("touchmove.zoom",null).on("touchend.zoom",null),q.selectAll("g.gnode").on("mousedown.drag",null);A&&(v.select(".background").style("cursor","crosshair"),v.call(b.brusher))}}function h(){A=D=!1;v.call(b.brusher).on("mousedown.brush",null).on("touchstart.brush",null).on("touchmove.brush",
null).on("touchend.brush",null);v.select(".background").style("cursor","auto");p.call(b.zoomer);q.selectAll("g.gnode").call(F)}var b=this;b.options={displayAllLinks:!1,labelInterval:10,applyForce:!0,initialSize:[200,200],allowPanningAndZooming:!0,cssFileLocation:"css/fornac.css",transitionDuration:500};if(1<arguments.length)for(var u in g)b.options.hasOwnProperty(u)&&(b.options[u]=g[u]);b.options.svgW=b.options.initialSize[0];b.options.svgH=b.options.initialSize[1];d3.scale.category20();var m=null,
t=null,x=d3.scale.linear().domain([0,b.options.svgW]).range([0,b.options.svgW]),E=d3.scale.linear().domain([0,b.options.svgH]).range([0,b.options.svgH]),H=b.graph={nodes:[],links:[]};b.linkStrengths={pseudoknot:0,proteinChain:0,chainChain:0,intermolecule:10,other:10};b.displayParameters={displayBackground:"true",displayNumbering:"true",displayNodeOutline:"true",displayNodeLabel:"true",displayLinks:"true",displayPseudoknotLinks:"true",displayProteinLinks:"true"};b.colorScheme="structure";b.customColors=
{};b.animation=b.options.applyForce;b.deaf=!1;b.rnas={};b.extraLinks=[];b.createInitialLayout=function(d,e){var f={sequence:"",name:"empty",positions:[],labelInterval:b.options.labelInterval,avoidOthers:!0,uids:[],circularizeExternal:!0};if(2==arguments.length)for(var h in e)f.hasOwnProperty(h)&&(f[h]=e[h]);rg=new RNAGraph(f.sequence,d,f.name);rg.circularizeExternal=f.circularizeExternal;rnaJson=rg.recalculateElements();0===f.positions.length&&(f.positions=simpleXyCoordinates(rnaJson.pairtable));
return rnaJson=rnaJson.elementsToJson().addUids(f.uids).addPositions("nucleotide",f.positions).addLabels(1,f.labelInterval).reinforceStems().reinforceLoops().connectFakeNodes().reassignLinkUids()};b.addRNA=function(d,e){var f=b.createInitialLayout(d,e);1===arguments.length&&(e={});"avoidOthers"in e?b.addRNAJSON(f,e.avoidOthers):b.addRNAJSON(f,!0);return f};b.addRNAJSON=function(d,e){var f,h;e&&(f=0<b.graph.nodes.length?d3.max(b.graph.nodes.map(function(b){return b.x})):0,h=d3.min(d.nodes.map(function(b){return b.x})),
d.nodes.forEach(function(b){b.x+=f-h;b.px+=f-h}));d.nodes.forEach(function(b){b.rna=d});b.rnas[d.uid]=d;b.recalculateGraph();b.update();b.centerView()};b.transitionRNA=function(d,e){function f(b,d){0===b.size()&&setTimeout(d,g);var e=0;b.each(function(){++e}).each("end",function(){--e||d.apply(this,arguments)})}function h(){b.createNewLinks(m.enter());b.graph.links=m.data();b.updateStyle();"undefined"!=typeof e&&e()}var g=b.options.transitionDuration,k={uids:b.graph.nodes.filter(function(b){return"nucleotide"==
b.nodeType}).map(function(b){return b.uid})},l=b.createInitialLayout(d,k),k=n.selectAll("g.gnode").data(l.nodes,nodeKey),g=b.options.transitionDuration;0===g?k.attr("transform",function(b){return"translate("+[b.x,b.y]+")"}):k.transition().attr("transform",function(b){return"translate("+[b.x,b.y]+")"}).duration(g);var m=w.selectAll("line.link").data(l.links,linkKey),l=b.createNewNodes(k.enter()).attr("transform",function(b){return"undefined"!=typeof b.x&&"undefined"!=typeof b.y?"translate(0,0)":""});
0===g?k.exit().remove():k.exit().transition().attr("transform",function(b){return"undefined"!=typeof b.x&&"undefined"!=typeof b.y?"translate(0,0)":""});b.graph.nodes=k.data();b.updateStyle();b.centerView(g);m.exit().remove();0===g?(m.attr("x1",function(b){return b.source.x}).attr("y1",function(b){return b.source.y}).attr("x2",function(b){return b.target.x}).attr("y2",function(b){return b.target.y}),b.createNewLinks(m.enter()),b.graph.links=m.data(),b.updateStyle()):m.transition().attr("x1",function(b){return b.source.x}).attr("y1",
function(b){return b.source.y}).attr("x2",function(b){return b.target.x}).attr("y2",function(b){return b.target.y}).duration(g).call(f,h);0===g?l.attr("transform",function(b){return"undefined"!=typeof b.x&&"undefined"!=typeof b.y?"translate("+[b.x,b.y]+")":""}):l.transition().attr("transform",function(b){return"undefined"!=typeof b.x&&"undefined"!=typeof b.y?"translate("+[b.x,b.y]+")":""})};b.recalculateGraph=function(d){b.graph.nodes=[];b.graph.links=[];for(var e in b.rnas)b.graph.nodes=b.graph.nodes.concat(b.rnas[e].nodes),
b.graph.links=b.graph.links.concat(b.rnas[e].links);for(var f={},h=0;h<b.graph.nodes.length;h++)f[b.graph.nodes[h].uid]=b.graph.nodes[h];b.graph.links.forEach(function(b){b.source=f[b.source.uid];b.target=f[b.target.uid]});for(h=0;h<b.extraLinks.length;h++){b.extraLinks[h].target.uid in f||console.log("not there:",b.extraLinks[h]);b.extraLinks[h].source=f[b.extraLinks[h].source.uid];b.extraLinks[h].target=f[b.extraLinks[h].target.uid];if("intermolecule"==b.extraLinks[h].linkType)for(fakeLinks=b.graph.links.filter(function(d){return(d.source==
b.extraLinks[h].source||d.source==b.extraLinks[h].target||d.target==b.extraLinks[h].source||d.target==b.extraLinks[h].source)&&"fake"==d.linkType}),d=0;d<fakeLinks.length;d++)e=b.graph.links.indexOf(fakeLinks[d]),b.graph.links.splice(e,1);H.links.push(b.extraLinks[h])}};b.addNodes=function(d){d.links.forEach(function(b){"number"==typeof b.source&&(b.source=d.nodes[b.source]);"number"==typeof b.target&&(b.target=d.nodes[b.target])});0<b.graph.nodes.length?(maxX=d3.max(b.graph.nodes.map(function(b){return b.x})),
maxY=d3.max(b.graph.nodes.map(function(b){return b.y}))):maxY=maxX=0;d.nodes.forEach(function(d){d.rna.uid in b.rnas||(b.rnas[d.rna.uid]=d.rna);d.x+=maxX;d.px+=maxX});r=new RNAGraph("","");r.nodes=d.nodes;r.links=d.links;b.recalculateGraph();b.update();b.centerView()};b.addCustomColors=function(d){b.customColors=d};b.clearNodes=function(){b.graph.nodes=[];b.graph.links=[];b.rnas={};b.extraLinks=[];b.update()};b.toJSON=function(){return JSON.stringify({rnas:b.rnas,extraLinks:b.extraLinks},function(b,
d){if("rna"!=b)return d},"\t")};b.fromJSON=function(d){var e,f;try{var h=JSON.parse(d);e=h.rnas;f=h.extraLinks}catch(g){throw g;}for(var k in e)"rna"==e[k].type?(r=new RNAGraph,r.seq=e[k].seq,r.dotbracket=e[k].dotbracket,r.circular=e[k].circular,r.pairtable=e[k].pairtable,r.uid=e[k].uid,r.structName=e[k].structName,r.nodes=e[k].nodes,r.links=e[k].links,r.rnaLength=e[k].rnaLength,r.elements=e[k].elements,r.nucsToNodes=e[k].nucsToNodes,r.pseudoknotPairs=e[k].pseudoknotPairs):(r=new ProteinGraph,r.size=
e[k].size,r.nodes=e[k].nodes,r.uid=e[k].uid),b.addRNAJSON(r,!1);f.forEach(function(d){b.extraLinks.push(d)});b.recalculateGraph();b.update()};b.setSize=function(){var d=$(l).width(),e=$(l).height();b.options.svgW=d;b.options.svgH=e;x.range([0,d]).domain([0,d]);E.range([0,e]).domain([0,e]);b.zoomer.x(x).y(E);b.brusher.x(x).y(E);B.attr("width",d).attr("height",e);y.attr("width",d).attr("height",e);b.centerView()};b.setOutlineColor=function(b){n.selectAll("g.gnode").select("[node_type=nucleotide]").style("fill",
b)};b.changeColorScheme=function(d){n.selectAll("[node_type=protein]").classed("protein",!0).attr("r",function(b){return b.radius});n.selectAll("g.gnode");n.selectAll("g.gnode").selectAll("circle");var e=n.selectAll("g.gnode").select("[node_type=nucleotide]");b.colorScheme=d;"sequence"==d?(scale=d3.scale.ordinal().range(["#dbdb8d","#98df8a","#ff9896","#aec7e8","#aec7e8"]).domain(["A","C","G","U","T"]),e.style("fill",function(b){return scale(b.name)})):"structure"==d?(scale=d3.scale.category10().domain("smiethx".split("")).range("lightgreen #ff9896 #dbdb8d lightsalmon lightcyan lightblue transparent".split(" ")),
e.style("fill",function(b){return scale(b.elemType)})):"positions"==d?e.style("fill",function(b){scale=d3.scale.linear().range(["#98df8a","#dbdb8d","#ff9896"]).interpolate(d3.interpolateLab).domain([1,1+(b.rna.rnaLength-1)/2,b.rna.rnaLength]);return scale(b.num)}):"custom"==d&&(scale=d3.scale.linear().interpolate(d3.interpolateLab).domain(b.customColors.domain).range(b.customColors.range),e.style("fill",function(d){return"undefined"==typeof b.customColors?"white":b.customColors.colorValues.hasOwnProperty(d.structName)&&
b.customColors.colorValues[d.structName].hasOwnProperty(d.num)?(moleculeColors=b.customColors.colorValues[d.structName],k(moleculeColors,d,scale)):b.customColors.colorValues.hasOwnProperty("")?(moleculeColors=b.customColors.colorValues[""],k(moleculeColors,d,scale)):"white"}))};window.addEventListener("resize",b.setSize,!1);b.zoomer=d3.behavior.zoom().scaleExtent([.1,10]).x(x).y(E).on("zoomstart",function(){var b=n.selectAll("g.gnode").selectAll(".outline_node");b.each(function(b){b.selected=!1;b.previouslySelected=
!1});b.classed("selected",!1)}).on("zoom",function(){q.attr("transform","translate("+d3.event.translate+") scale("+d3.event.scale+")")});d3.select(l).select("svg").remove();var y=d3.select(l).attr("tabindex",1).on("keydown.brush",f).on("keyup.brush",h).each(function(){this.focus()}).append("svg:svg").attr("width",b.options.svgW).attr("height",b.options.svgH).attr("id","plotting-area"),z=y.append("svg:style");$.get(b.options.cssFileLocation,function(b){z.text(b.replace(/[\s\n]/g,""))});b.options.svg=
y;var p=y.append("svg:g").on("mousemove",function(){m&&(mpos=d3.mouse(q.node()),C.attr("x1",m.x).attr("y1",m.y).attr("x2",mpos[0]).attr("y2",mpos[1]))}).on("mousedown",function(){}).on("mouseup",function(){m&&C.attr("class","drag_line_hidden");t=m=null});b.options.allowPanningAndZooming&&p.call(b.zoomer);var B=p.append("svg:rect").attr("width",b.options.svgW).attr("height",b.options.svgH).attr("fill","white").attr("stroke","grey").attr("stroke-width",1).attr("id","zrect"),v=p.append("g").datum(function(){return{selected:!1,
previouslySelected:!1}}).attr("class","brush"),q=p.append("svg:g"),w=q.append("svg:g"),n=q.append("svg:g");b.brusher=d3.svg.brush().x(x).y(E).on("brushstart",function(b){n.selectAll("g.gnode").selectAll(".outline_node").each(function(b){b.previouslySelected=A&&b.selected})}).on("brush",function(){var d=n.selectAll("g.gnode").selectAll(".outline_node"),e=d3.event.target.extent();d.classed("selected",function(d){return d.selected=b.options.applyForce&&d.previouslySelected^(e[0][0]<=d.x&&d.x<e[1][0]&&
e[0][1]<=d.y&&d.y<e[1][1])})}).on("brushend",function(){d3.event.target.clear();d3.select(this).call(d3.event.target)});v.call(b.brusher).on("mousedown.brush",null).on("touchstart.brush",null).on("touchmove.brush",null).on("touchend.brush",null);v.select(".background").style("cursor","auto");b.getBoundingBoxTransform=function(){if(0===b.graph.nodes.length)return{translate:[0,0],scale:1};minX=d3.min(b.graph.nodes.map(function(b){return b.x}));minY=d3.min(b.graph.nodes.map(function(b){return b.y}));
maxX=d3.max(b.graph.nodes.map(function(b){return b.x}));maxY=d3.max(b.graph.nodes.map(function(b){return b.y}));molWidth=maxX-minX;molHeight=maxY-minY;widthRatio=b.options.svgW/(molWidth+1);heightRatio=b.options.svgH/(molHeight+1);minRatio=.8*Math.min(widthRatio,heightRatio);newMolWidth=molWidth*minRatio;newMolHeight=molHeight*minRatio;xTrans=-minX*minRatio+(b.options.svgW-newMolWidth)/2;yTrans=-minY*minRatio+(b.options.svgH-newMolHeight)/2;return{translate:[xTrans,yTrans],scale:minRatio}};b.centerView=
function(d){0===arguments.length&&(d=0);var e=b.getBoundingBoxTransform();null!==e&&(q.transition().attr("transform","translate("+e.translate+") scale("+e.scale+")").duration(d),b.zoomer.translate(e.translate),b.zoomer.scale(e.scale))};b.force=d3.layout.force().charge(function(b){return-30}).chargeDistance(300).friction(.35).linkDistance(function(b){return 15*b.value}).linkStrength(function(d){return d.linkType in b.linkStrengths?b.linkStrengths[d.linkType]:b.linkStrengths.other}).gravity(0).nodes(b.graph.nodes).links(b.graph.links).chargeDistance(110).size([b.options.svgW,
b.options.svgH]);var C=q.append("line").attr("class","drag_line").attr("x1",0).attr("y1",0).attr("x2",0).attr("y2",0),D=!1,A=!1;b.resumeForce=function(){b.animation&&b.force.resume()};var F=d3.behavior.drag().on("dragstart",function(e){d3.event.sourceEvent.stopPropagation();e.selected||A||n.selectAll("g.gnode").selectAll(".outline_node").classed("selected",function(d){return d.selected=b.options.applyForce&&(d.previouslySelected=!1)});d3.select(this).select(".outline_node").classed("selected",function(d){e.previouslySelected=
e.selected;return e.selected=b.options.applyForce&&!0});d(e).each(function(b){b.fixed|=2})}).on("drag",function(e){d(e).each(function(b){b.x+=d3.event.dx;b.y+=d3.event.dy;b.px+=d3.event.dx;b.py+=d3.event.dy});b.resumeForce();d3.event.sourceEvent.preventDefault()}).on("dragend",function(b){d(b).each(function(b){b.fixed&=-7})});d3.select(l).on("keydown",f).on("keyup",h).on("contextmenu",function(){d3.event.preventDefault()});linkKey=function(b){return b.uid};nodeKey=function(b){return key=b.uid};updateRnaGraph=
function(d){var e=d.getPositions("nucleotide"),f=d.getPositions("label"),h=d.getUids();d.recalculateElements().elementsToJson().addPseudoknots().addPositions("nucleotide",e).addUids(h).addLabels(1,b.options.labelInterval).addPositions("label",f).reinforceStems().reinforceLoops().updateLinkUids()};removeLink=function(d){index=b.graph.links.indexOf(d);if(-1<index){if(d.source.rna==d.target.rna){var e=d.source.rna;e.addPseudoknots();e.pairtable[d.source.num]=0;e.pairtable[d.target.num]=0;updateRnaGraph(e)}else extraLinkIndex=
b.extraLinks.indexOf(d),b.extraLinks.splice(extraLinkIndex,1);b.recalculateGraph()}b.update()};linkClick=function(b){D&&(b.linkType in{backbone:!0,fake:!0,fake_fake:!0,label_link:!0}||removeLink(b))};b.addLink=function(d){d.source.rna==d.target.rna?(r=d.source.rna,r.pairtable[d.source.num]=d.target.num,r.pairtable[d.target.num]=d.source.num,updateRnaGraph(r)):(d.linkType="intermolecule",b.extraLinks.push(d));b.recalculateGraph();b.update()};nodeMouseclick=function(d){d3.event.defaultPrevented||(A||
n.selectAll("g.gnode").selectAll(".outline_node").classed("selected",function(d){return d.selected=b.options.applyForce&&(d.previouslySelected=!1)}),d3.select(this).select("circle").classed("selected",d.selected=b.options.applyForce&&!d.previouslySelected))};nodeMouseup=function(d){if(m)if(t=d,t==m)t=m=null;else{d={source:m,target:t,linkType:"basepair",value:1,uid:generateUUID()};for(i=0;i<b.graph.links.length;i++){if(b.graph.links[i].source==m||b.graph.links[i].target==m||b.graph.links[i].source==
t||b.graph.links[i].target==t)if("basepair"==b.graph.links[i].linkType||"pseudoknot"==b.graph.links[i].linkType)return;if((b.graph.links[i].source==t&&b.graph.links[i].target==m||b.graph.links[i].source==m&&b.graph.links[i].target==t)&&"backbone"==b.graph.links[i].linkType)return}"middle"!=t.nodeType&&"middle"!=m.nodeType&&"label"!=t.nodeType&&"label"!=m.nodeType&&b.addLink(d)}};nodeMousedown=function(d){d.selected||A||n.selectAll("g.gnode").selectAll(".outline_node").classed("selected",function(b){return b.selected=
b.previouslySelected=!1});d3.select(this).classed("selected",function(e){d.previouslySelected=d.selected;return d.selected=b.options.applyForce&&!0});D&&(m=d,C.attr("class","drag_line").attr("x1",m.x).attr("y1",m.y).attr("x2",m.x).attr("y2",m.y))};b.startAnimation=function(){b.animation=!0;q.selectAll("g.gnode").call(F);b.force.start()};b.stopAnimation=function(){b.animation=!1;q.selectAll("g.gnode").on("mousedown.drag",null);b.force.stop()};b.setFriction=function(d){b.force.friction(d);b.resumeForce()};
b.setCharge=function(d){b.force.charge(d);b.resumeForce()};b.setGravity=function(d){b.force.gravity(d);b.resumeForce()};b.setPseudoknotStrength=function(d){b.linkStrengths.pseudoknot=d;b.update()};b.displayBackground=function(d){b.displayParameters.displayBackground=d;b.updateStyle()};b.displayNumbering=function(d){b.displayParameters.displayNumbering=d;b.updateStyle()};b.displayNodeOutline=function(d){b.displayParameters.displayNodeOutline=d;b.updateStyle()};b.displayNodeLabel=function(d){b.displayParameters.displayNodeLabel=
d;b.updateStyle()};b.displayLinks=function(d){b.displayParameters.displayLinks=d;b.updateStyle()};b.displayPseudoknotLinks=function(d){b.displayParameters.displayPseudoknotLinks=d;b.updateStyle()};b.displayProteinLinks=function(d){b.displayParameters.displayProteinLinks=d;b.updateStyle()};b.updateStyle=function(){B.classed("transparent",!b.displayParameters.displayBackground);n.selectAll("[node_type=label]").classed("transparent",!b.displayParameters.displayNumbering);n.selectAll("[label_type=label]").classed("transparent",
!b.displayParameters.displayNumbering);w.selectAll("[linkType=label_link]").classed("transparent",!b.displayParameters.displayNumbering);y.selectAll("circle").classed("hidden_outline",!b.displayParameters.displayNodeOutline);n.selectAll("[label_type=nucleotide]").classed("transparent",!b.displayParameters.displayNodeLabel);y.selectAll("[link_type=real],[link_type=basepair],[link_type=backbone],[link_type=pseudoknot],[link_type=protein_chain],[link_type=chain_chain]").classed("transparent",!b.displayParameters.displayLinks);
y.selectAll("[link_type=pseudoknot]").classed("transparent",!b.displayParameters.displayPseudoknotLinks);y.selectAll("[link_type=protein_chain]").classed("transparent",!b.displayParameters.displayProteinLinks);w.selectAll("[link_type=fake]").classed("transparent",!b.options.displayAllLinks);w.selectAll("[link_type=fake_fake]").classed("transparent",!b.options.displayAllLinks)};b.createNewLinks=function(b){b=b.append("svg:line");b.append("svg:title").text(linkKey);b.classed("link",!0).attr("x1",function(b){return b.source.x}).attr("y1",
function(b){return b.source.y}).attr("x2",function(b){return b.target.x}).attr("y2",function(b){return b.target.y}).attr("link_type",function(b){return b.linkType}).attr("class",function(b){return d3.select(this).attr("class")+" "+b.linkType}).attr("pointer-events",function(b){return"fake"==b.linkType?"none":"all"});return b};b.createNewNodes=function(b){b=b.append("g").classed("noselect",!0).classed("gnode",!0).attr("struct_name",function(b){return b.structName}).attr("transform",function(b){return"undefined"!=
typeof b.x&&"undefined"!=typeof b.y?"translate("+[b.x,b.y]+")":""}).each(function(b){b.selected=b.previouslySelected=!1});b.call(F).on("mousedown",nodeMousedown).on("mousedrag",function(b){}).on("mouseup",nodeMouseup).on("click",nodeMouseclick).transition().duration(750).ease("elastic").attr("r",6.5);b.filter(function(b){return"nucleotide"==b.nodeType||"label"==b.nodeType||"protein"==b.nodeType}).append("svg:circle").attr("class","outline_node").attr("r",function(b){return b.radius+1});var d=b.append("svg:circle").attr("class",
"node").classed("label",function(b){return"label"==b.nodeType}).attr("r",function(b){return"middle"==b.nodeType?0:b.radius}).attr("node_type",function(b){return b.nodeType});b.append("text").text(function(b){return b.name}).attr("text-anchor","middle").attr("font-size",8).attr("font-weight","bold").attr("y",2.5).attr("class","node-label").attr("label_type",function(b){return b.nodeType}).append("svg:title").text(function(b){return"nucleotide"==b.nodeType?b.structName+":"+b.num:""});d.append("svg:title").text(function(b){return"nucleotide"==
b.nodeType?b.structName+":"+b.num:""});return b};nodeTooltip=function(b){nodeTooltips={};nodeTooltips.nucleotide=b.num;nodeTooltips.label="";nodeTooltips.pseudo="";nodeTooltips.middle="";nodeTooltips.protein=b.structName;return nodeTooltips[b.nodeType]};b.update=function(){b.force.nodes(b.graph.nodes).links(b.graph.links);b.animation&&b.force.start();var d=w.selectAll("line.link").data(b.graph.links,linkKey);d.attr("class","").classed("link",!0).attr("link_type",function(b){return b.linkType}).attr("class",
function(b){return d3.select(this).attr("class")+" "+b.linkType});var f=d.enter();b.createNewLinks(f);d.exit().remove();domain=[0,1,2,3,4,5,6,7,8,9];d3.scale.category10().domain(domain);var h=n.selectAll("g.gnode").data(b.graph.nodes,nodeKey);gnodesEnter=h.enter();b.createNewNodes(gnodesEnter);h.exit().remove();realNodes=b.graph.nodes.filter(function(b){return"nucleotide"==b.nodeType||"label"==b.nodeType});xlink=b.displayFakeLinks?d:w.selectAll("[link_type=real],[link_type=pseudoknot],[link_type=protein_chain],[link_type=chain_chain],[link_type=label_link],[link_type=backbone],[link_type=basepair],[link_type=fake],[link_type=intermolecule]");
xlink.on("click",linkClick);b.force.on("tick",function(){for(var b=d3.geom.quadtree(realNodes),d=0,f=realNodes.length;++d<f;)b.visit(e(realNodes[d]));xlink.attr("x1",function(b){return b.source.x}).attr("y1",function(b){return b.source.y}).attr("x2",function(b){return b.target.x}).attr("y2",function(b){return b.target.y});h.attr("transform",function(b){return"translate("+[b.x,b.y]+")"})});b.changeColorScheme(b.colorScheme);b.animation&&b.force.start();b.updateStyle()};b.setSize()};var numberSort=function(l,g){return l-g};function generateUUID(){var l=(new Date).getTime();return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(g){var k=(l+16*Math.random())%16|0;l=Math.floor(l/16);return("x"==g?k:k&3|8).toString(16)})}function isNormalInteger(l){return/^\+?(0|[1-9]\d*)$/.test(l)}"undefined"===typeof String.prototype.trim&&(String.prototype.trim=function(){return String(this).replace(/^\s+|\s+$/g,"")});
function ColorScheme(l){var g=this;g.colorsText=l;g.parseRange=function(g){for(var d=g.split(","),e=[],f=0;f<d.length;f++){var h=d[f].split("-");if(1==h.length)e.push(parseInt(h[0]));else if(2==h.length)for(var b=parseInt(h[0]),h=parseInt(h[1]);b<=h;b++)e.push(b);else console.log("Malformed range (too many dashes):",g)}return e};g.parseColorText=function(k){k=k.split("\n");for(var d="",e=1,f={colorValues:{"":{}},range:["white","steelblue"]},h=[],b=0;b<k.length;b++)if(">"==k[b][0])d=k[b].trim().slice(1),
e=1,f.colorValues[d]={};else{words=k[b].trim().split(/[\s]+/);for(var l=0;l<words.length;l++)if(isNaN(words[l]))if(0===words[l].search("range"))parts=words[l].split("="),partsRight=parts[1].split(":"),f.range=[partsRight[0],partsRight[1]];else if(0==words[l].search("domain"))parts=words[l].split("="),partsRight=parts[1].split(":"),f.domain=[partsRight[0],partsRight[1]];else{parts=words[l].split(":");nums=g.parseRange(parts[0]);color=parts[1];for(var m=0;m<nums.length;m++)isNaN(color)?f.colorValues[d][nums[m]]=
color:(f.colorValues[d][nums[m]]=+color,h.push(Number(color)))}else f.colorValues[d][e]=Number(words[l]),e+=1,h.push(Number(words[l]))}"domain"in f||(f.domain=[Math.min.apply(null,h),Math.max.apply(null,h)]);g.colorsJson=f;return g};g.normalizeColors=function(){var k,d;for(d in g.colorsJson){var e=Number.MAX_VALUE,f=Number.MIN_VALUE,h;for(h in g.colorsJson.colorValues[d])k=g.colorsJson.colorValues[d][h],"number"==typeof k&&(k<e&&(e=k),k>f&&(f=k));for(h in g.colorsJson.colorValues[d])k=g.colorsJson.colorValues[d][h],
"number"==typeof k&&(g.colorsJson.colorValues[d][h]=(k-e)/(f-e))}return g};g.parseColorText(g.colorsText);return g}
function ProteinGraph(l,g,k){var d=this;d.type="protein";d.size=g;d.nodes=[{name:"P",num:1,radius:3*Math.sqrt(g),rna:d,nodeType:"protein",structName:l,elemType:"p",size:g,uid:generateUUID()}];d.links=[];d.uid=generateUUID();d.addUids=function(e){for(var f=0;f<e.length;f++)d.nodes[f].uid=e[f];return d};d.getUids=function(){uids=[];for(var e=0;e<d.dotbracket.length;e++)uids.push(d.nodes[e].uid);return uids}}
function RNAGraph(l,g,k){var d=this;d.type="rna";d.circularizeExternal=!1;0==arguments.length?(d.seq="",d.dotbracket="",d.structName=""):(d.seq=l,d.dotbracket=g,d.structName=k);d.circular=!1;0<d.dotbracket.length&&"*"==d.dotbracket[d.dotbracket.length-1]&&(d.dotbracket=d.dotbracket.slice(0,d.dotbracket.length-1),d.circular=!0);d.uid=generateUUID();d.rnaLength=d.dotbracket.length;d.elements=[];d.pseudoknotPairs=[];d.nucsToNodes={};d.addUids=function(e){for(var f=d.nodes.filter(function(b){return"nucleotide"==
b.nodeType}),h=0;h<e.length&&h<f.length;h++)f[h].uid=e[h];return d};d.computePairtable=function(){d.pairtable=rnaUtilities.dotbracketToPairtable(d.dotbracket)};d.computePairtable();d.addPositions=function(e,f){for(var h=d.nodes.filter(function(b){return b.nodeType==e}),b=0;b<h.length;b++)h[b].x=f[b][0],h[b].px=f[b][0],h[b].y=f[b][1],h[b].py=f[b][1];return d};d.getPositions=function(e){positions=[];nucleotideNodes=d.nodes.filter(function(d){return d.nodeType==e});for(var f=0;f<nucleotideNodes.length;f++)positions.push([nucleotideNodes[f].x,
nucleotideNodes[f].y]);return positions};d.getUids=function(){uids=[];for(var e=0;e<d.dotbracket.length;e++)uids.push(d.nodes[e].uid);return uids};d.reinforceStems=function(){pt=d.pairtable;relevantElements=elements.filter(function(d){return"s"==d[0]&&4<=d[2].length});for(var e=0;e<relevantElements.length;e++){allNucs=relevantElements[e][2];nucs=allNucs.slice(0,allNucs.length/2);for(var f=0;f<nucs.length-1;f++)d.addFakeNode([nucs[f],nucs[f+1],pt[nucs[f+1]],pt[nucs[f]]])}return d};d.reinforceLoops=
function(){var e=function(b){return 0!==b&&b<=d.dotbracket.length};for(i=0;i<d.elements.length;i++)if("s"!=d.elements[i][0]&&(d.circularizeExternal||"e"!=d.elements[i][0])){var f=d.elements[i][2].filter(e);if("e"==d.elements[i][0]){var h={name:"",num:-1,radius:0,rna:d,nodeType:"middle",elemType:"f",nucs:[],x:d.nodes[d.rnaLength-1].x,y:d.nodes[d.rnaLength-1].y,px:d.nodes[d.rnaLength-1].px,py:d.nodes[d.rnaLength-1].py,uid:generateUUID()},b={name:"",num:-1,radius:0,rna:d,nodeType:"middle",elemType:"f",
nucs:[],x:d.nodes[0].x,y:d.nodes[0].y,px:d.nodes[0].px,py:d.nodes[0].py,uid:generateUUID()};f.push(d.nodes.length+1);f.push(d.nodes.length+2);d.nodes.push(h);d.nodes.push(b)}d.addFakeNode(f)}return d};d.updateLinkUids=function(){for(var e=0;e<d.links.length;e++)d.links[e].uid=d.links[e].source.uid+d.links[e].target.uid;return d};d.addFakeNode=function(e){for(var f=6.283/(2*e.length),f=18/(2*Math.tan(f)),h="",b=0;b<e.length;b++)h+=d.nodes[e[b]-1].uid;h={name:"",num:-1,radius:f,rna:d,nodeType:"middle",
elemType:"f",nucs:e,uid:h};d.nodes.push(h);coordsCounted=newY=newX=0;f=3.14159*(e.length-2)/(2*e.length);f=.5/Math.cos(f);for(j=0;j<e.length;j++)0===e[j]||e[j]>d.dotbracket.length||(d.links.push({source:d.nodes[e[j]-1],target:d.nodes[d.nodes.length-1],linkType:"fake",value:f,uid:generateUUID()}),4<e.length&&d.links.push({source:d.nodes[e[j]-1],target:d.nodes[e[(j+Math.floor(e.length/2))%e.length]-1],linkType:"fake",value:2*f,uid:generateUUID()}),ia=3.14159*(e.length-2)/e.length,c=2*Math.cos(1.570795-
ia/2),d.links.push({source:d.nodes[e[j]-1],target:d.nodes[e[(j+2)%e.length]-1],linkType:"fake",value:c}),fromNode=d.nodes[e[j]-1],"x"in fromNode&&(newX+=fromNode.x,newY+=fromNode.y,coordsCounted+=1));0<coordsCounted&&(h.x=newX/coordsCounted,h.y=newY/coordsCounted,h.px=h.x,h.py=h.y);return d};d.connectFakeNodes=function(){for(var e={},f=d.nodes.filter(function(b){return"middle"==b.nodeType}),h=new Set,b=1;b<=d.nodes.length;b++)e[b]=[];for(b=0;b<f.length;b++)for(var g=f[b],k=0;k<g.nucs.length;k++){for(var l=
g.nucs[k],x=0;x<e[l].length;x++)h.has(JSON.stringify([e[l][x].uid,g.uid].sort()))||(d.links.push({source:e[l][x],target:g,value:(e[l][x].radius+g.radius)/18,linkType:"fake_fake"}),h.add(JSON.stringify([e[l][x].uid,g.uid].sort())));e[l].push(g)}return d};d.elementsToJson=function(){pt=d.pairtable;elements=d.elements;d.nodes=[];d.links=[];elemTypes={};d.elements.sort();for(var e=0;e<d.elements.length;e++)for(nucs=d.elements[e][2],j=0;j<nucs.length;j++)elemTypes[nucs[j]]=d.elements[e][0];for(e=1;e<=
pt[0];e++)d.nodes.push({name:d.seq[e-1],num:e,radius:6,rna:d,nodeType:"nucleotide",structName:d.structName,elemType:elemTypes[e],uid:generateUUID()});for(e=1;e<=pt[0];e++)0!==pt[e]&&d.links.push({source:d.nodes[e-1],target:d.nodes[pt[e]-1],linkType:"basepair",value:1,uid:generateUUID()}),1<e&&d.links.push({source:d.nodes[e-2],target:d.nodes[e-1],linkType:"backbone",value:1,uid:generateUUID()});for(e=0;e<d.pseudoknotPairs.length;e++)d.links.push({source:d.nodes[d.pseudoknotPairs[e][0]-1],target:d.nodes[d.pseudoknotPairs[e][1]-
1],linkType:"pseudoknot",value:1,uid:generateUUID()});d.circular&&d.links.push({source:d.nodes[0],target:d.nodes[d.rnaLength-1],linkType:"backbone",value:1,uid:generateUUID()});return d};d.ptToElements=function(e,f,h,b){var g=[],k=[h-1],l=[b+1];if(h>b)return[];for(;0===e[h];h++)k.push(h);for(;0===e[b];b--)l.push(b);if(h>b)return k.push(h),0===f?[["e",f,k.sort(numberSort)]]:[["h",f,k.sort(numberSort)]];if(e[h]!=b){for(k.push(h);h<=b;){g=g.concat(d.ptToElements(e,f,h,e[h]));k.push(e[h]);for(h=e[h]+
1;0===e[h]&&h<=b;h++)k.push(h);k.push(h)}k.pop();k=k.concat(l);0<k.length&&(0===f?g.push(["e",f,k.sort(numberSort)]):g.push(["m",f,k.sort(numberSort)]));return g}e[h]===b&&(k.push(h),l.push(b),combined=k.concat(l),4<combined.length&&(0===f?g.push(["e",f,k.concat(l).sort(numberSort)]):g.push(["i",f,k.concat(l).sort(numberSort)])));for(l=[];e[h]===b&&h<b;)l.push(h),l.push(b),h+=1,--b,f+=1;g.push(["s",f,l.sort(numberSort)]);return g.concat(d.ptToElements(e,f,h,b))};d.addLabels=function(e,f){0===arguments.length&&
(e=1,f=10);1===arguments.length&&(f=10);if(0===f)return d;0>=f&&console.log("The label interval entered in invalid:",f);for(i=1;i<=pt[0];i++)if(0===i%f){var h,b;thisNode=d.nodes[i-1];1==d.rnaLength?(nextVec=[thisNode.x-15,thisNode.y],prevVec=[thisNode.x-15,thisNode.y]):(prevNode=1==i?d.nodes[d.rnaLength-1]:d.nodes[i-2],nextNode=i==d.rnaLength?d.nodes[0]:d.nodes[i],0!==d.pairtable[nextNode.num]&&0!==d.pairtable[prevNode.num]&&0!==d.pairtable[thisNode.num]&&(prevNode=nextNode=d.nodes[d.pairtable[thisNode.num]-
1]),0===d.pairtable[thisNode.num]||0!==d.pairtable[nextNode.num]&&0!==d.pairtable[prevNode.num]?(nextVec=[nextNode.x-thisNode.x,nextNode.y-thisNode.y],prevVec=[prevNode.x-thisNode.x,prevNode.y-thisNode.y]):(nextVec=[thisNode.x-nextNode.x,thisNode.y-nextNode.y],prevVec=[thisNode.x-prevNode.x,thisNode.y-prevNode.y]));combinedVec=[nextVec[0]+prevVec[0],nextVec[1]+prevVec[1]];vecLength=Math.sqrt(combinedVec[0]*combinedVec[0]+combinedVec[1]*combinedVec[1]);normedVec=[combinedVec[0]/vecLength,combinedVec[1]/
vecLength];offsetVec=[-15*normedVec[0],-15*normedVec[1]];h=d.nodes[i-1].x+offsetVec[0];b=d.nodes[i-1].y+offsetVec[1];newNode={name:i+e-1,num:-1,radius:6,rna:d,nodeType:"label",structName:d.structName,elemType:"l",x:h,y:b,px:h,py:b,uid:generateUUID()};newLink={source:d.nodes[i-1],target:newNode,value:1,linkType:"label_link",uid:generateUUID()};d.nodes.push(newNode);d.links.push(newLink)}return d};d.recalculateElements=function(){d.removePseudoknots();d.elements=d.ptToElements(d.pairtable,0,1,d.dotbracket.length);
if(d.circular&&(externalLoop=d.elements.filter(function(d){if("e"==d[0])return!0}),0<externalLoop.length)){eloop=externalLoop[0];nucs=eloop[2].sort(numberSort);prev=nucs[0];hloop=!0;numGreater=0;for(var e=1;e<nucs.length;e++)1<nucs[e]-prev&&(numGreater+=1),prev=nucs[e];eloop[0]=1==numGreater?"h":2==numGreater?"i":"m"}return d};d.reassignLinkUids=function(){var e;for(e=0;e<d.links.length;e++)d.links[e].uid=d.links[e].source.uid+d.links[e].target.uid;return d};d.removePseudoknots=function(){d.pseudoknotPairs=
1<d.pairtable.length?rnaUtilities.removePseudoknotsFromPairtable(d.pairtable):[];return d};d.addPseudoknots=function(){var e=d.pairtable,f=d.pseudoknotPairs;for(i=0;i<f.length;i++)e[f[i][0]]=f[i][1],e[f[i][1]]=f[i][0];d.pseudoknotPairs=[];return d};0<d.rnaLength&&d.recalculateElements()}
moleculesToJson=function(l){for(var g={},k=[],d=[],e=0;e<l.molecules.length;e++){var f=l.molecules[e];"rna"==f.type?(rg=new RNAGraph(f.seq,f.ss,f.header),rg.circularizeExternal=!0,rg.elementsToJson().addPositions("nucleotide",f.positions).addLabels().reinforceStems().reinforceLoops()):"protein"==f.type&&(rg=new ProteinGraph(f.header,f.size));rg.addUids(f.uids);for(f=0;f<rg.nodes.length;f++)g[rg.nodes[f].uid]=rg.nodes[f];k.push(rg)}for(e=0;e<l.extraLinks.length;e++)link=l.extraLinks[e],link.source=
g[link.source],link.target=g[link.target],link.uid=generateUUID(),d.push(link);return{graphs:k,extraLinks:d}};numberSort=function(l,g){return l-g};
function RNAUtilities(){var l=this;l.bracketLeft="([{<ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");l.bracketRight=")]}>abcdefghijklmnopqrstuvwxyz".split("");l.inverseBrackets=function(g){res={};for(i=0;i<g.length;i++)res[g[i]]=i;return res};l.maximumMatching=function(g){var k=g[0];mm=Array(k+1);for(var d=0;d<=k;d++){mm[d]=Array(k+1);for(var e=d;e<=k;e++)mm[d][e]=0}for(var f=0,d=k-0-1;0<d;d--)for(e=d+0+1;e<=k;e++){for(var f=mm[d][e-1],h=e-0-1;h>=d;h--)g[h]===e&&(f=Math.max(f,(h>d?mm[d][h-1]:0)+1+(0<e-h-1?
mm[h+1][e-1]:0)));mm[d][e]=f}return mm};l.backtrackMaximumMatching=function(g,k){var d=Array.apply(null,Array(g.length)).map(function(){return 0});l.mmBt(g,d,k,1,g.length-1);return d};l.mmBt=function(g,k,d,e,f){var h=g[e][f];if(!(0>f-e-1))if(g[e][f-1]==h)l.mmBt(g,k,d,e,f-1);else{for(var b=f-0-1;b>=e;b--)if(d[f]===b&&(b>e?g[e][b-1]:0)+(0<f-b-1?g[b+1][f-1]:0)+1==h){k[b]=f;k[f]=b;e<b&&l.mmBt(g,k,d,e,b-1);l.mmBt(g,k,d,b+1,f-1);return}console.log("FAILED!!!"+e+","+f+": backtracking failed!")}};l.dotbracketToPairtable=
function(g){pt=Array.apply(null,Array(g.length+1)).map(Number.prototype.valueOf,0);pt[0]=g.length;stack={};for(i=0;i<l.bracketLeft.length;i++)stack[i]=[];inverseBracketLeft=l.inverseBrackets(l.bracketLeft);inverseBracketRight=l.inverseBrackets(l.bracketRight);for(i=0;i<g.length;i++)if(a=g[i],ni=i+1,"."==a)pt[ni]=0;else if(a in inverseBracketLeft)stack[inverseBracketLeft[a]].push(ni);else if(a in inverseBracketRight)j=stack[inverseBracketRight[a]].pop(),pt[ni]=j,pt[j]=ni;else throw"Unknown symbol in dotbracket string";
for(key in stack)if(0<stack[key].length)throw"Unmatched base at position "+stack[key][0];return pt};l.insertIntoStack=function(g,k,d){for(k=0;0<g[k].length&&g[k][g[k].length-1]<d;)k+=1;g[k].push(d);return k};l.deleteFromStack=function(g,k){for(var d=0;0===g[d].length||g[d][g[d].length-1]!=k;)d+=1;g[d].pop();return d};l.pairtableToDotbracket=function(g){stack={};for(i=0;i<g[0];i++)stack[i]=[];seen={};res="";for(i=1;i<g[0]+1;i++){if(0!==g[i]&&g[i]in seen)throw"Invalid pairtable contains duplicate entries";
seen[g[i]]=!0;res=0===g[i]?res+".":g[i]>i?res+l.bracketLeft[l.insertIntoStack(stack,i,g[i])]:res+l.bracketRight[l.deleteFromStack(stack,i)]}return res};l.findUnmatched=function(g,k,d){for(var e=[],f=[],h=d,b=k;b<=d;b++)0!==g[b]&&(g[b]<k||g[b]>d)&&f.push([b,g[b]]);for(b=k;b<=h;b++){for(;0===g[b]&&b<=h;)b++;for(d=g[b];g[b]===d;)b++,d--;e=e.concat(l.findUnmatched(g,b,d))}0<f.length&&e.push(f);return e};l.removePseudoknotsFromPairtable=function(g){for(var k=l.maximumMatching(g),k=l.backtrackMaximumMatching(k,
g),d=[],e=1;e<g.length;e++)g[e]<e||k[e]==g[e]||(d.push([e,g[e]]),g[g[e]]=0,g[e]=0);return d}}rnaUtilities=new RNAUtilities;simpleXyCoordinates=function(l){var g=[],k=[],d,e;d=l[0];var f=Array.apply(null,Array(d+5)).map(Number.prototype.valueOf,0),h=Array.apply(null,Array(16+Math.floor(d/5))).map(Number.prototype.valueOf,0),b=Array.apply(null,Array(16+Math.floor(d/5))).map(Number.prototype.valueOf,0);lp=stk=0;var u=Math.PI/2;loop=function(d,e,g){var k=2,l=0,y=0,z,p,B,v,q,w,n,C=Array.apply(null,Array(1+2*Math.floor((e-d)/5))).map(Number.prototype.valueOf,0);z=d-1;for(e++;d!=e;)if((p=g[d])&&0!=d){k+=2;B=d;v=p;C[++l]=B;C[++l]=
v;d=p+1;q=B;w=v;n=0;do B++,v--,n++;while(g[B]==v);p=n-2;if(2<=n&&(f[q+1+p]+=u,f[w-1-p]+=u,f[q]+=u,f[w]+=u,2<n))for(;1<=p;p--)f[q+p]=Math.PI,f[w-p]=Math.PI;b[++stk]=n;loop(B,v,g)}else d++,k++,y++;d=Math.PI*(k-2)/k;C[++l]=e;e=0>z?0:z;for(z=1;z<=l;z++){g=C[z]-e;for(p=0;p<=g;p++)f[e+p]+=d;if(z>l)break;e=C[++z]}h[++lp]=y};loop(0,d+1,l);h[lp]-=2;e=0;g[0]=100;k[0]=100;poss=[];poss.push([g[0],k[0]]);for(l=1;l<d;l++)g[l]=g[l-1]+15*Math.cos(e),k[l]=k[l-1]+15*Math.sin(e),poss.push([g[l],k[l]]),e+=Math.PI-f[l+
1];return poss};
